/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Utils.ButtonGroupGT;
import bean.KhachHang;
import bean.LoaiThanhVien;
import controller.ControllerKhachHang;
import controller.ControllerLoaiThanhVien;
import java.awt.BorderLayout;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;
import library.JChooserDateToDate;
import library.ValidateDB;
import model.ModelKhachHang;
import render.LoaiThanhVienComboboxModel;
import render.QuocTichComboboxModel;

/**
 *
 * @author vuongluis
 */
public class PnUser extends javax.swing.JPanel {

    private ControllerKhachHang controller;
    private ControllerLoaiThanhVien controllerLoaiThanhVien;
    /**
     * Creates new form PnUser
     */
    public PnUser() {
        initComponents();
        controller = new ControllerKhachHang(tbMain);
        controllerLoaiThanhVien = new ControllerLoaiThanhVien(tbMain);
        controller.loadTable();
        
        controllerLoaiThanhVien.loadLoaiThanhVien(this.cbLoaiThanhVien, false, null);
        this.cbQuocTich.setModel(new QuocTichComboboxModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGioiTinh = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfKhachHang = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        cbLoaiThanhVien = new javax.swing.JComboBox();
        tfCMT = new javax.swing.JTextField();
        tfNgheNghiep = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfSoDienThoai = new javax.swing.JTextField();
        cbQuocTich = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfDiaChi = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        tfNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btNhapLai = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfKhachHangF = new javax.swing.JTextField();
        tfCMTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfNgheNghiepF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfDiaChiF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbLoaiThanhVienF = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        tfQuocTichF = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btTimKiemF = new javax.swing.JButton();
        btNhapLaiF = new javax.swing.JButton();
        btDong = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();

        setBackground(new java.awt.Color(242, 242, 242));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane1.setDividerSize(6);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết khách hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Số thứ tự:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tên khách hàng:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Số chứng minh thư:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Địa chỉ:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Nghề nghiệp:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Số điện thoại:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Quốc tịch:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Loại Thành viên:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Giới tính:");

        tfID.setEditable(false);
        tfID.setPreferredSize(new java.awt.Dimension(6, 24));

        tfKhachHang.setPreferredSize(new java.awt.Dimension(6, 24));

        btnGioiTinh.add(rdNam);
        rdNam.setText("Nam");

        btnGioiTinh.add(rdNu);
        rdNu.setText("Nữ");

        cbLoaiThanhVien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---- Chọn Thành Viên ----" }));
        cbLoaiThanhVien.setMinimumSize(new java.awt.Dimension(138, 24));
        cbLoaiThanhVien.setPreferredSize(new java.awt.Dimension(144, 24));

        tfCMT.setPreferredSize(new java.awt.Dimension(6, 24));

        tfNgheNghiep.setPreferredSize(new java.awt.Dimension(6, 24));

        tfEmail.setPreferredSize(new java.awt.Dimension(6, 24));

        tfSoDienThoai.setPreferredSize(new java.awt.Dimension(6, 24));

        cbQuocTich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---- Chọn Quốc Tịch ----" }));
        cbQuocTich.setMinimumSize(new java.awt.Dimension(138, 24));
        cbQuocTich.setPreferredSize(new java.awt.Dimension(144, 24));

        tfDiaChi.setColumns(20);
        tfDiaChi.setLineWrap(true);
        tfDiaChi.setRows(5);
        tfDiaChi.setWrapStyleWord(true);
        jScrollPane3.setViewportView(tfDiaChi);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Ngày sinh:");

        tfNgaySinh.setPreferredSize(new java.awt.Dimension(91, 24));

        jPanel7.setBackground(new java.awt.Color(242, 242, 242));

        btThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel7.add(btThem);

        btSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btSua.setText("Sữa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        jPanel7.add(btSua);

        btNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btNhapLai.setText("Nhập lại");
        btNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapLaiActionPerformed(evt);
            }
        });
        jPanel7.add(btNhapLai);

        btXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.gif"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jPanel7.add(btXoa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbQuocTich, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCMT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNgheNghiep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfSoDienThoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbLoaiThanhVien, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addComponent(tfKhachHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(rdNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdNu))
                                    .addComponent(tfID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rdNam)
                    .addComponent(rdNu))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbLoaiThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(242, 242, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm thông tin", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Tên khách hàng:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Số chứng minh thư:");

        tfKhachHangF.setMinimumSize(new java.awt.Dimension(6, 24));
        tfKhachHangF.setPreferredSize(new java.awt.Dimension(6, 24));

        tfCMTF.setMinimumSize(new java.awt.Dimension(6, 24));
        tfCMTF.setPreferredSize(new java.awt.Dimension(6, 24));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Nghề nghiệp:");

        tfNgheNghiepF.setMinimumSize(new java.awt.Dimension(6, 24));
        tfNgheNghiepF.setPreferredSize(new java.awt.Dimension(6, 24));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Địa chỉ:");

        tfDiaChiF.setMinimumSize(new java.awt.Dimension(6, 24));
        tfDiaChiF.setPreferredSize(new java.awt.Dimension(6, 24));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Loại thành viên:");

        cbLoaiThanhVienF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLoaiThanhVienF.setPreferredSize(new java.awt.Dimension(56, 24));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Quốc tịch:");

        tfQuocTichF.setMinimumSize(new java.awt.Dimension(6, 24));
        tfQuocTichF.setPreferredSize(new java.awt.Dimension(6, 24));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cbLoaiThanhVienF, 0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(29, 29, 29)
                        .addComponent(tfNgheNghiepF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfKhachHangF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCMTF, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(44, 44, 44)
                        .addComponent(tfDiaChiF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(26, 26, 26)
                        .addComponent(tfQuocTichF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(tfKhachHangF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCMTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfNgheNghiepF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfDiaChiF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbLoaiThanhVienF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfQuocTichF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(242, 242, 242)));
        jPanel6.setLayout(new java.awt.GridLayout(3, 1, 15, 15));

        btTimKiemF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btTimKiemF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iSearch.png"))); // NOI18N
        btTimKiemF.setText("Tìm kiếm");
        jPanel6.add(btTimKiemF);

        btNhapLaiF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhapLaiF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iReset.png"))); // NOI18N
        btNhapLaiF.setText("Nhập lại");
        jPanel6.add(btNhapLaiF);

        btDong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iClose.png"))); // NOI18N
        btDong.setText("Đóng");
        jPanel6.add(btDong);

        jPanel4.add(jPanel6, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(242, 242, 242));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbMain.setAutoCreateRowSorter(true);
        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMainMousePressed(evt);
            }
        });
        tbMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbMainKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbMain);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbMainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMainKeyReleased
        // TODO add your handling code here:
        this.setForm();
    }//GEN-LAST:event_tbMainKeyReleased

    private void tbMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMainMousePressed
        // TODO add your handling code here:
        this.setForm();
    }//GEN-LAST:event_tbMainMousePressed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        try{
            String hoTen = tfKhachHang.getText();
            String gioiTinh = new ButtonGroupGT().getText(btnGioiTinh);
            
            Date utilDate = new JChooserDateToDate().getTime(tfNgaySinh.getDate());
            java.sql.Timestamp ngaySinh = new java.sql.Timestamp(utilDate.getTime());
            
            String quocTich = (String) new QuocTichComboboxModel().getElementAt(cbQuocTich.getSelectedIndex());        
            String scmt = tfCMT.getText();
            String ngheNghiep = tfNgheNghiep.getText();
            String email = tfEmail.getText();
            String soDienThoai = tfSoDienThoai.getText();
            LoaiThanhVien loaiThanhVien = new LoaiThanhVienComboboxModel().getElementAt(cbLoaiThanhVien.getSelectedIndex());
            String diaChi = tfDiaChi.getText();            
            
            KhachHang obj = new KhachHang(0, hoTen, gioiTinh, ngaySinh, scmt, email, diaChi, ngheNghiep, soDienThoai, quocTich, loaiThanhVien.getMatv());
            if(isValid(obj, "add")){
                if(!new ValidateDB().socmt_exist(String.valueOf(obj.getSoCMT()))){
                    int result = controller.addItem(obj);
                    if(result > 0){
                        this.resetForm();
                        JOptionPane.showConfirmDialog(new PnUser(), "<html><p style=\"color:blue; font-weight:bold;\">Thêm khách hàng thành công!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
                    }else{
                        JOptionPane.showConfirmDialog(new PnUser(), "<html><p style=\"color:red; font-weight:bold;\">Thêm khách hàng thất bại!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
                    }
                }else{
                    JOptionPane.showConfirmDialog(new PnUser(), "<html><p style=\"color:red; font-weight:bold;\">Khách hàng tồn tại trong hệ thống!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
                }
            }
        }catch(NumberFormatException ex){
            JOptionPane.showConfirmDialog(new PnUser(), "<html><p style=\"color:red; font-weight:bold;\">Vui lòng nhập thông tin vào trường!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int row = tbMain.getSelectedRow();
        if(row >= 0){
            try{
                int id = Integer.parseInt(tfID.getText());
                String hoTen = tfKhachHang.getText();
                String gioiTinh = new ButtonGroupGT().getText(btnGioiTinh);

                Date utilDate = new JChooserDateToDate().getTime(tfNgaySinh.getDate());
                java.sql.Timestamp ngaySinh = new java.sql.Timestamp(utilDate.getTime());

                String quocTich = (String) new QuocTichComboboxModel().getElementAt(cbQuocTich.getSelectedIndex());        
                String scmt = new ModelKhachHang().getItem(id).getSoCMT();
                String ngheNghiep = tfNgheNghiep.getText();
                
                String email = tfEmail.getText();
                String soDienThoai = new ModelKhachHang().getItem(id).getSoDienThoai();
                
                LoaiThanhVien loaiThanhVien = new LoaiThanhVienComboboxModel().getElementAt(cbLoaiThanhVien.getSelectedIndex());
                String diaChi = tfDiaChi.getText();
                
                KhachHang obj = new KhachHang(id, hoTen, gioiTinh, ngaySinh, scmt, email, diaChi, ngheNghiep, soDienThoai, quocTich, loaiThanhVien.getMatv());
                
                if(isValid(obj, "edit")){
                    if(!new ValidateDB().socmt_existver(obj.getSoCMT(),id)){
                        int result = controller.editItem(obj,row);
                        if(result > 0){
                            this.resetForm();
                            JOptionPane.showConfirmDialog(new PnUser(), "<html><p style=\"color:blue; font-weight:bold;\">Cập nhật khách hàng thành công!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
                        }else{
                            JOptionPane.showConfirmDialog(new PnUser(), "<html><p style=\"color:red; font-weight:bold;\">Cập nhật khách hàng thất bại!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
                        }
                    }else{
                        JOptionPane.showConfirmDialog(new PnUser(), "<html><p style=\"color:red; font-weight:bold;\">Khách hàng tồn tại trong hệ thống!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
                    }
                }
            }catch(NumberFormatException ex){
                JOptionPane.showConfirmDialog(new PnUser(), "<html><p style=\"color:red; font-weight:bold;\">Vui lòng nhập thông tin vào trường trống!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showConfirmDialog(new PnUser(), "<html><p style=\"color:red; font-weight:bold;\">Bạn chưa chọn dòng để cập nhật!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapLaiActionPerformed
        // TODO add your handling code here:
        this.resetForm();
    }//GEN-LAST:event_btNhapLaiActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int row = tbMain.getSelectedRow();
        if(row >= 0){
            // When i delete new from table, way to good to delete get id from textfield
            int id = Integer.parseInt(tfID.getText());
            if(controller.delItem(id,row)>0){
                this.resetForm();
                JOptionPane.showMessageDialog(new PnUser(), "<html><p style=\"color:blue; font-weight:bold;\">Xóa khách hàng thành công!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(new PnUser(), "<html><p style=\"color:red; font-weight:bold;\">Xóa khách hàng thất bại!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(new PnUser(), "<html><p style=\"color:red; font-weight:bold;\">Bạn chưa chọn dòng để xóa!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDong;
    private javax.swing.JButton btNhapLai;
    private javax.swing.JButton btNhapLaiF;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTimKiemF;
    private javax.swing.JButton btXoa;
    private javax.swing.ButtonGroup btnGioiTinh;
    private javax.swing.JComboBox cbLoaiThanhVien;
    private javax.swing.JComboBox<String> cbLoaiThanhVienF;
    private javax.swing.JComboBox<String> cbQuocTich;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tbMain;
    private javax.swing.JTextField tfCMT;
    private javax.swing.JTextField tfCMTF;
    private javax.swing.JTextArea tfDiaChi;
    private javax.swing.JTextField tfDiaChiF;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfKhachHang;
    private javax.swing.JTextField tfKhachHangF;
    private com.toedter.calendar.JDateChooser tfNgaySinh;
    private javax.swing.JTextField tfNgheNghiep;
    private javax.swing.JTextField tfNgheNghiepF;
    private javax.swing.JTextField tfQuocTichF;
    private javax.swing.JTextField tfSoDienThoai;
    // End of variables declaration//GEN-END:variables

    private void setForm() {
        int row = tbMain.getSelectedRow();
        int id = Integer.parseInt(tbMain.getValueAt(row, 0).toString());
        tfID.setText(String.valueOf(id));
        
        String hoTen = tbMain.getValueAt(row, 1).toString();
        tfKhachHang.setText(hoTen);
        
        String gioiTinh = tbMain.getValueAt(row, 2).toString();
        if(gioiTinh.equals("Nam")){
            rdNam.setSelected(true);
        }else if(gioiTinh.equals("Nữ")){
            rdNu.setSelected(true);
        }
        KhachHang item = new ModelKhachHang().getItem(id);
        Timestamp ngaySinh = item.getNgaySinh();
        tfNgaySinh.setDate(ngaySinh);
        
        cbQuocTich.setModel(new QuocTichComboboxModel((String) tbMain.getValueAt(row, 9)));
        
        String  scmt = tbMain.getValueAt(row, 4).toString();
        tfCMT.setText(scmt);
        
        String ngheNghiep = tbMain.getValueAt(row, 7).toString();
        tfNgheNghiep.setText(ngheNghiep);
        
        String email = tbMain.getValueAt(row, 5).toString();
        tfEmail.setText(email);
        
        String soDienThoai = tbMain.getValueAt(row, 8).toString();
        tfSoDienThoai.setText(soDienThoai);
        
        cbLoaiThanhVien.setModel(new LoaiThanhVienComboboxModel(tbMain.getValueAt(row, 10).toString()));
        
        String diaChi = tbMain.getValueAt(row, 6).toString();
        tfDiaChi.setText(diaChi);
    }

    private void resetForm() {
        tfID.setText("");
        tfKhachHang.setText("");
        rdNam.setSelected(false);
        rdNu.setSelected(false);
        tfNgaySinh.setDate(new Date());
        cbQuocTich.setModel(new QuocTichComboboxModel());
        tfCMT.setText("");
        tfNgheNghiep.setText("");
        tfEmail.setText("");
        tfSoDienThoai.setText("");
        controllerLoaiThanhVien.loadLoaiThanhVien(this.cbLoaiThanhVien, false, null);
        tfDiaChi.setText("");
    }
    
    private boolean isValid(KhachHang obj, String function) {
        boolean result = true;
        switch(function){
            case "add":
                break;
            case "edit":
                break;
            case "del":
                if(obj.getMaKH()<0){
                    JOptionPane.showConfirmDialog(new PnUser(), "<html><p style=\"color:red; font-weight:bold;\">Bạn chưa chọn dòng để xóa!</p></html>","Thông báo",JOptionPane.WARNING_MESSAGE);
                    result = false;
                }
                break;
        }
        return result;
    }
}
