/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package render;

import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author vuongluis
 */
public class QuocTichComboboxModel implements ComboBoxModel{

    private ArrayList<String> alItems = new ArrayList<String>();
    private Object object = new Object();
    
    public QuocTichComboboxModel(){
        alItems.add("AFGHANISTAN");
        alItems.add("AILAND ISLANDS");
        alItems.add("ALBANIA");
        alItems.add("ALGERIA");
        alItems.add("ALGERIA");
        alItems.add("ANDORRA");
        alItems.add("ANGOLA");
        alItems.add("ANGUILLA");
        alItems.add("ANTARCTICA");
        alItems.add("ANTIGUA AND BARBUDA");
        alItems.add("ARGENTINA");
        alItems.add("ARMENIA");
        alItems.add("ARUBA");
        alItems.add("AUSTRALIA");
        alItems.add("AUSTRIA");
        alItems.add("AZERBAIJAN");
        alItems.add("BAHAMAS");
        alItems.add("BAHRAIN");
        alItems.add("BANGLADESH");
        alItems.add("BARBADOS");
        alItems.add("BELARUS");
        alItems.add("BELGIUM");
        alItems.add("BELIZE");
        alItems.add("BENIN");
        alItems.add("BERMUDA");
        alItems.add("BHUTAN");
        alItems.add("BOLIVIA");
        alItems.add("BOSNIA AND HERZEGOVINA");
        alItems.add("BOTSWANA");
        alItems.add("BOUVET ISLAND");
        alItems.add("BRAZIL");
        alItems.add("BRITISH INDIAN OCEAN TERRITORY");
        alItems.add("BRUNEI DARUSSALAM");
        alItems.add("BULGARIA");
        alItems.add("BURKINA FASO");
        alItems.add("BURUNDI");
        alItems.add("CAMBODIA");
        alItems.add("CAMEROON");
        alItems.add("CANADA");
        alItems.add("CAPE VERDE");
        alItems.add("CAYMAN ISLANDS");
        alItems.add("CENTRAL AFRICAN REPUBLIC");
        alItems.add("CHAD");
        alItems.add("CHILE");
        alItems.add("CHINA");
        alItems.add("CHRISTMAS ISLAND");
        alItems.add("COCOS (KEELING) ISLANDS");
        alItems.add("COLOMBIA");
        alItems.add("COMOROS");
        alItems.add("CONGO");
        alItems.add("CONGO, THE DEMOCRATIC REPUBLIC OF THE");
        alItems.add("COOK ISLANDS");
        alItems.add("COSTA RICA");
        alItems.add("COOTE D'IVOIRE");
        alItems.add("CROATIA");
        alItems.add("CUBA");
        alItems.add("CYPRUS");
        alItems.add("CZECH REPUBLIC");
        alItems.add("DENMARK");
        alItems.add("DJIBOUTI");
        alItems.add("DOMINICA");
        alItems.add("DOMINICAN REPUBLIC");
        alItems.add("ECUADOR");
        alItems.add("EGYPT");
        alItems.add("EL SALVADOR");
        alItems.add("EQUATORIAL GUINEA");
        alItems.add("ERITREA");
        alItems.add("ESTONIA");
        alItems.add("ETHIOPIA");
        alItems.add("FALKLAND ISLANDS (MALVINAS)");
        alItems.add("FAROE ISLANDS");
        alItems.add("FIJI");
        alItems.add("FINLAND");
        alItems.add("FRANCE");
        alItems.add("FRENCH GUIANA");
        alItems.add("FRENCH POLYNESIA");
        alItems.add("FRENCH SOUTHERN TERRITORIES");
        alItems.add("GABON");
        alItems.add("GAMBIA");
        alItems.add("GEORGIA");
        alItems.add("GERMANY");
        alItems.add("GHANA");
        alItems.add("GIBRALTAR");
        alItems.add("GREECE");
        alItems.add("GREENLAND");
        alItems.add("GRENADA");
        alItems.add("GUADELOUPE");
        alItems.add("GUAM");
        alItems.add("GUATEMALA");
        alItems.add("GUINEA");
        alItems.add("GUINEA-BISSAU");
        alItems.add("GUYANA");
        alItems.add("HAITI");
        alItems.add("HEARD ISLAND AND MCDONALD ISLANDS");
        alItems.add("HOLY SEE (VATICAN CITY STATE)");
        alItems.add("HONDURAS");
        alItems.add("HONG KONG");
        alItems.add("HUNGARY");
        alItems.add("ICELAND");
        alItems.add("INDIA");
        alItems.add("INDONESIA");
        alItems.add("IRAN, ISLAMIC REPUBLIC OF");
        alItems.add("IRAQ");
        alItems.add("IRELAND");
        alItems.add("ISRAEL");
        alItems.add("ITALY");
        alItems.add("JAMAICA");
        alItems.add("JAPAN");
        alItems.add("JORDAN");
        alItems.add("KAZAKHSTAN");
        alItems.add("KENYA");
        alItems.add("KIRIBATI");
        alItems.add("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF");
        alItems.add("KOREA, REPUBLIC OF");
        alItems.add("KUWAIT");
        alItems.add("KYRGYZSTAN");
        alItems.add("LAO PEOPLE'S DEMOCRATIC REPUBLIC");
        alItems.add("LATVIA");
        alItems.add("LEBANON");
        alItems.add("LESOTHO");
        alItems.add("LIBERIA");
        alItems.add("LIBYAN ARAB JAMAHIRIYA");
        alItems.add("LIECHTENSTEIN");
        alItems.add("LITHUANIA");
        alItems.add("LUXEMBOURG");
        alItems.add("MACAO");
        alItems.add("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF");
        alItems.add("MADAGASCAR");
        alItems.add("MALAWI");
        alItems.add("MALAYSIA");
        alItems.add("MALDIVES");
        alItems.add("MALI");
        alItems.add("MALTA");
        alItems.add("MARSHALL ISLANDS");
        alItems.add("MARTINIQUE");
        alItems.add("MAURITANIA");
        alItems.add("MAURITIUS");
        alItems.add("MAYOTTE");
        alItems.add("MEXICO");
        alItems.add("MICRONESIA, FEDERATED STATES OF");
        alItems.add("MOLDOVA, REPUBLIC OF");
        alItems.add("MONACO");
        alItems.add("MONGOLIA");
        alItems.add("MONTSERRAT");
        alItems.add("MOROCCO");
        alItems.add("MOZAMBIQUE");
        alItems.add("MYANMAR");
        alItems.add("NAMIBIA");
        alItems.add("NAURU");
        alItems.add("NEPAL");
        alItems.add("NETHERLANDS");
        alItems.add("NETHERLANDS ANTILLES");
        alItems.add("NEW CALEDONIA");
        alItems.add("NEW ZEALAND");
        alItems.add("NICARAGUA");
        alItems.add("NIGER");
        alItems.add("NIGERIA");
        alItems.add("NIUE");
        alItems.add("NORFOLK ISLAND");
        alItems.add("NORTHERN MARIANA ISLANDS");
        alItems.add("NORWAY");
        alItems.add("OMAN");
        alItems.add("PAKISTAN");
        alItems.add("PALAU");
        alItems.add("PALESTINIAN TERRITORY, OCCUPIED");
        alItems.add("PANAMA");
        alItems.add("PAPUA NEW GUINEA");
        alItems.add("PARAGUAY");
        alItems.add("PERU");
        alItems.add("PHILIPPINES");
        alItems.add("PITCAIRN");
        alItems.add("POLAND");
        alItems.add("PORTUGAL");
        alItems.add("PUERTO RICO");
        alItems.add("QATAR");
        alItems.add("RESUNION");
        alItems.add("ROMANIA");
        alItems.add("RUSSIAN FEDERATION");
        alItems.add("RWANDA");
        alItems.add("SAINT HELENA");
        alItems.add("SAINT KITTS AND NEVIS");
        alItems.add("SAINT LUCIA");
        alItems.add("SAINT PIERRE AND MIQUELON");
        alItems.add("SAINT VINCENT AND THE GRENADINES");
        alItems.add("SAMOA");
        alItems.add("SAN MARINO");
        alItems.add("SAO TOME AND PRINCIPE");
        alItems.add("SAUDI ARABIA");
        alItems.add("SENEGAL");
        alItems.add("SERBIA AND MONTENEGRO");
        alItems.add("SEYCHELLES");
        alItems.add("SIERRA LEONE");
        alItems.add("SINGAPORE");
        alItems.add("SLOVAKIA");
        alItems.add("SLOVENIA");
        alItems.add("SOLOMON ISLANDS");
        alItems.add("SOMALIA");
        alItems.add("SOUTH AFRICA");
        alItems.add("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS");
        alItems.add("SPAIN");
        alItems.add("SRI LANKA");
        alItems.add("SUDAN");
        alItems.add("SURINAME");
        alItems.add("SVALBARD AND JAN MAYEN");
        alItems.add("SWAZILAND");
        alItems.add("SWEDEN");
        alItems.add("SWITZERLAND");
        alItems.add("SYRIAN ARAB REPUBLIC");
        alItems.add("TAIWAN, PROVINCE OF CHINA");
        alItems.add("TAJIKISTAN");
        alItems.add("TANZANIA, UNITED REPUBLIC OF");
        alItems.add("THAILAND");
        alItems.add("TIMOR-LESTE");
        alItems.add("TOGO");
        alItems.add("TOKELAU");
        alItems.add("TONGA");
        alItems.add("TRINIDAD AND TOBAGO");
        alItems.add("TUNISIA");
        alItems.add("TURKEY");
        alItems.add("TURKMENISTAN");
        alItems.add("TURKS AND CAICOS ISLANDS");
        alItems.add("TUVALU");
        alItems.add("UGANDA");
        alItems.add("UKRAINE");
        alItems.add("UNITED ARAB EMIRATES");
        alItems.add("UNITED KINGDOM");
        alItems.add("UNITED STATES");
        alItems.add("UNITED STATES MINOR OUTLYING ISLANDS");
        alItems.add("URUGUAY");
        alItems.add("UZBEKISTAN");
        alItems.add("VANUATU");
        alItems.add("Vatican City State see HOLY SEE");
        alItems.add("VENEZUELA");
        alItems.add("VIET NAM");
        alItems.add("VIRGIN ISLANDS, BRITISH");
        alItems.add("VIRGIN ISLANDS, U.S.");
        alItems.add("WALLIS AND FUTUNA");
        alItems.add("WESTERN SAHARA");
        alItems.add("YEMEN");
        alItems.add("ZAMBIA");
        alItems.add("ZIMBABWE");
        object = alItems.get(233);
    }
    
    public QuocTichComboboxModel(String temp){
        alItems.add("AFGHANISTAN");
        alItems.add("AILAND ISLANDS");
        alItems.add("ALBANIA");
        alItems.add("ALGERIA");
        alItems.add("ALGERIA");
        alItems.add("ANDORRA");
        alItems.add("ANGOLA");
        alItems.add("ANGUILLA");
        alItems.add("ANTARCTICA");
        alItems.add("ANTIGUA AND BARBUDA");
        alItems.add("ARGENTINA");
        alItems.add("ARMENIA");
        alItems.add("ARUBA");
        alItems.add("AUSTRALIA");
        alItems.add("AUSTRIA");
        alItems.add("AZERBAIJAN");
        alItems.add("BAHAMAS");
        alItems.add("BAHRAIN");
        alItems.add("BANGLADESH");
        alItems.add("BARBADOS");
        alItems.add("BELARUS");
        alItems.add("BELGIUM");
        alItems.add("BELIZE");
        alItems.add("BENIN");
        alItems.add("BERMUDA");
        alItems.add("BHUTAN");
        alItems.add("BOLIVIA");
        alItems.add("BOSNIA AND HERZEGOVINA");
        alItems.add("BOTSWANA");
        alItems.add("BOUVET ISLAND");
        alItems.add("BRAZIL");
        alItems.add("BRITISH INDIAN OCEAN TERRITORY");
        alItems.add("BRUNEI DARUSSALAM");
        alItems.add("BULGARIA");
        alItems.add("BURKINA FASO");
        alItems.add("BURUNDI");
        alItems.add("CAMBODIA");
        alItems.add("CAMEROON");
        alItems.add("CANADA");
        alItems.add("CAPE VERDE");
        alItems.add("CAYMAN ISLANDS");
        alItems.add("CENTRAL AFRICAN REPUBLIC");
        alItems.add("CHAD");
        alItems.add("CHILE");
        alItems.add("CHINA");
        alItems.add("CHRISTMAS ISLAND");
        alItems.add("COCOS (KEELING) ISLANDS");
        alItems.add("COLOMBIA");
        alItems.add("COMOROS");
        alItems.add("CONGO");
        alItems.add("CONGO, THE DEMOCRATIC REPUBLIC OF THE");
        alItems.add("COOK ISLANDS");
        alItems.add("COSTA RICA");
        alItems.add("COOTE D'IVOIRE");
        alItems.add("CROATIA");
        alItems.add("CUBA");
        alItems.add("CYPRUS");
        alItems.add("CZECH REPUBLIC");
        alItems.add("DENMARK");
        alItems.add("DJIBOUTI");
        alItems.add("DOMINICA");
        alItems.add("DOMINICAN REPUBLIC");
        alItems.add("ECUADOR");
        alItems.add("EGYPT");
        alItems.add("EL SALVADOR");
        alItems.add("EQUATORIAL GUINEA");
        alItems.add("ERITREA");
        alItems.add("ESTONIA");
        alItems.add("ETHIOPIA");
        alItems.add("FALKLAND ISLANDS (MALVINAS)");
        alItems.add("FAROE ISLANDS");
        alItems.add("FIJI");
        alItems.add("FINLAND");
        alItems.add("FRANCE");
        alItems.add("FRENCH GUIANA");
        alItems.add("FRENCH POLYNESIA");
        alItems.add("FRENCH SOUTHERN TERRITORIES");
        alItems.add("GABON");
        alItems.add("GAMBIA");
        alItems.add("GEORGIA");
        alItems.add("GERMANY");
        alItems.add("GHANA");
        alItems.add("GIBRALTAR");
        alItems.add("GREECE");
        alItems.add("GREENLAND");
        alItems.add("GRENADA");
        alItems.add("GUADELOUPE");
        alItems.add("GUAM");
        alItems.add("GUATEMALA");
        alItems.add("GUINEA");
        alItems.add("GUINEA-BISSAU");
        alItems.add("GUYANA");
        alItems.add("HAITI");
        alItems.add("HEARD ISLAND AND MCDONALD ISLANDS");
        alItems.add("HOLY SEE (VATICAN CITY STATE)");
        alItems.add("HONDURAS");
        alItems.add("HONG KONG");
        alItems.add("HUNGARY");
        alItems.add("ICELAND");
        alItems.add("INDIA");
        alItems.add("INDONESIA");
        alItems.add("IRAN, ISLAMIC REPUBLIC OF");
        alItems.add("IRAQ");
        alItems.add("IRELAND");
        alItems.add("ISRAEL");
        alItems.add("ITALY");
        alItems.add("JAMAICA");
        alItems.add("JAPAN");
        alItems.add("JORDAN");
        alItems.add("KAZAKHSTAN");
        alItems.add("KENYA");
        alItems.add("KIRIBATI");
        alItems.add("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF");
        alItems.add("KOREA, REPUBLIC OF");
        alItems.add("KUWAIT");
        alItems.add("KYRGYZSTAN");
        alItems.add("LAO PEOPLE'S DEMOCRATIC REPUBLIC");
        alItems.add("LATVIA");
        alItems.add("LEBANON");
        alItems.add("LESOTHO");
        alItems.add("LIBERIA");
        alItems.add("LIBYAN ARAB JAMAHIRIYA");
        alItems.add("LIECHTENSTEIN");
        alItems.add("LITHUANIA");
        alItems.add("LUXEMBOURG");
        alItems.add("MACAO");
        alItems.add("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF");
        alItems.add("MADAGASCAR");
        alItems.add("MALAWI");
        alItems.add("MALAYSIA");
        alItems.add("MALDIVES");
        alItems.add("MALI");
        alItems.add("MALTA");
        alItems.add("MARSHALL ISLANDS");
        alItems.add("MARTINIQUE");
        alItems.add("MAURITANIA");
        alItems.add("MAURITIUS");
        alItems.add("MAYOTTE");
        alItems.add("MEXICO");
        alItems.add("MICRONESIA, FEDERATED STATES OF");
        alItems.add("MOLDOVA, REPUBLIC OF");
        alItems.add("MONACO");
        alItems.add("MONGOLIA");
        alItems.add("MONTSERRAT");
        alItems.add("MOROCCO");
        alItems.add("MOZAMBIQUE");
        alItems.add("MYANMAR");
        alItems.add("NAMIBIA");
        alItems.add("NAURU");
        alItems.add("NEPAL");
        alItems.add("NETHERLANDS");
        alItems.add("NETHERLANDS ANTILLES");
        alItems.add("NEW CALEDONIA");
        alItems.add("NEW ZEALAND");
        alItems.add("NICARAGUA");
        alItems.add("NIGER");
        alItems.add("NIGERIA");
        alItems.add("NIUE");
        alItems.add("NORFOLK ISLAND");
        alItems.add("NORTHERN MARIANA ISLANDS");
        alItems.add("NORWAY");
        alItems.add("OMAN");
        alItems.add("PAKISTAN");
        alItems.add("PALAU");
        alItems.add("PALESTINIAN TERRITORY, OCCUPIED");
        alItems.add("PANAMA");
        alItems.add("PAPUA NEW GUINEA");
        alItems.add("PARAGUAY");
        alItems.add("PERU");
        alItems.add("PHILIPPINES");
        alItems.add("PITCAIRN");
        alItems.add("POLAND");
        alItems.add("PORTUGAL");
        alItems.add("PUERTO RICO");
        alItems.add("QATAR");
        alItems.add("RESUNION");
        alItems.add("ROMANIA");
        alItems.add("RUSSIAN FEDERATION");
        alItems.add("RWANDA");
        alItems.add("SAINT HELENA");
        alItems.add("SAINT KITTS AND NEVIS");
        alItems.add("SAINT LUCIA");
        alItems.add("SAINT PIERRE AND MIQUELON");
        alItems.add("SAINT VINCENT AND THE GRENADINES");
        alItems.add("SAMOA");
        alItems.add("SAN MARINO");
        alItems.add("SAO TOME AND PRINCIPE");
        alItems.add("SAUDI ARABIA");
        alItems.add("SENEGAL");
        alItems.add("SERBIA AND MONTENEGRO");
        alItems.add("SEYCHELLES");
        alItems.add("SIERRA LEONE");
        alItems.add("SINGAPORE");
        alItems.add("SLOVAKIA");
        alItems.add("SLOVENIA");
        alItems.add("SOLOMON ISLANDS");
        alItems.add("SOMALIA");
        alItems.add("SOUTH AFRICA");
        alItems.add("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS");
        alItems.add("SPAIN");
        alItems.add("SRI LANKA");
        alItems.add("SUDAN");
        alItems.add("SURINAME");
        alItems.add("SVALBARD AND JAN MAYEN");
        alItems.add("SWAZILAND");
        alItems.add("SWEDEN");
        alItems.add("SWITZERLAND");
        alItems.add("SYRIAN ARAB REPUBLIC");
        alItems.add("TAIWAN, PROVINCE OF CHINA");
        alItems.add("TAJIKISTAN");
        alItems.add("TANZANIA, UNITED REPUBLIC OF");
        alItems.add("THAILAND");
        alItems.add("TIMOR-LESTE");
        alItems.add("TOGO");
        alItems.add("TOKELAU");
        alItems.add("TONGA");
        alItems.add("TRINIDAD AND TOBAGO");
        alItems.add("TUNISIA");
        alItems.add("TURKEY");
        alItems.add("TURKMENISTAN");
        alItems.add("TURKS AND CAICOS ISLANDS");
        alItems.add("TUVALU");
        alItems.add("UGANDA");
        alItems.add("UKRAINE");
        alItems.add("UNITED ARAB EMIRATES");
        alItems.add("UNITED KINGDOM");
        alItems.add("UNITED STATES");
        alItems.add("UNITED STATES MINOR OUTLYING ISLANDS");
        alItems.add("URUGUAY");
        alItems.add("UZBEKISTAN");
        alItems.add("VANUATU");
        alItems.add("Vatican City State see HOLY SEE");
        alItems.add("VENEZUELA");
        alItems.add("VIET NAM");
        alItems.add("VIRGIN ISLANDS, BRITISH");
        alItems.add("VIRGIN ISLANDS, U.S.");
        alItems.add("WALLIS AND FUTUNA");
        alItems.add("WESTERN SAHARA");
        alItems.add("YEMEN");
        alItems.add("ZAMBIA");
        alItems.add("ZIMBABWE");
        for(int i = 0; i < alItems.size(); i++){
            if(alItems.get(i).equals(temp)){
                object = alItems.get(i);
            }
        }
    }
    
    @Override
    public void setSelectedItem(Object anItem) {
        object = anItem;
    }

    @Override
    public Object getSelectedItem() {
        return object;
    }

    @Override
    public int getSize() {
        return alItems.size();
    }

    @Override
    public Object getElementAt(int index) {
        return alItems.get(index);
    }

    @Override
    public void addListDataListener(ListDataListener l) {
        
    }

    @Override
    public void removeListDataListener(ListDataListener l) {
        
    }
    
}
